apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terminal-ingress
  namespace: terminal
spec:
  ingressClassName: cilium
  rules:
  - host: terminal.valentak.at
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: terminal-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: terminal-backend
            port:
              number: 8000

