apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: terminal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-lvm-r1
  resources:
    requests:
      storage: 5Gi

