apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: terminal
type: Opaque
stringData:
  POSTGRES_USER: terminal_user
  POSTGRES_PASSWORD: terminal_pass
  POSTGRES_DB: terminal_db

