apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terminal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/michelix/kubernetes-apps.git
    targetRevision: HEAD
    path: applications/terminal/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: terminal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

